config/routes.rb
Rails.application.routes.draw do
  resources :event_managements
  get 'calendar/home'
  resources :consultations
  resources :comments

devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  get '/users/sign_out'=> 'devise/sessions#destroy'
  get 'calendar/home'


end
  devise_for :users
  get "home/about" 
  get "posts/myposts"
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/event_management.rb
class EventManagement < ApplicationRecord
end

app/controllers/event_managements_controller.rb
class EventManagementsController < ApplicationController
  before_action :set_event_management, only: %i[ show edit update destroy ]

  # GET /event_managements or /event_managements.json
  def index
    @event_managements = EventManagement.all
  end

  # GET /event_managements/1 or /event_managements/1.json
  def show
  end

  # GET /event_managements/new
  def new
    @event_management = EventManagement.new
  end

  # GET /event_managements/1/edit
  def edit
  end

  # POST /event_managements or /event_managements.json
  def create
    @event_management = EventManagement.new(event_management_params)

    respond_to do |format|
      if @event_management.save
        format.html { redirect_to event_management_url(@event_management), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event_management }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_managements/1 or /event_managements/1.json
  def update
    respond_to do |format|
      if @event_management.update(event_management_params)
        format.html { redirect_to event_management_url(@event_management), notice: "Event management was successfully updated." }
        format.json { render :show, status: :ok, location: @event_management }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event_management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_managements/1 or /event_managements/1.json
  def destroy
    @event_management.destroy!

    respond_to do |format|
      format.html { redirect_to event_managements_url, notice: "Event management was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_management
      @event_management = EventManagement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_management_params
      params.require(:event_management).permit(:title, :description, :start_time, :end_time)
    end
end

app/helpers/event_managements_helper.rb
module EventManagementsHelper
end

app/views/event_managements/_event_management.html.erb
<div class="card" id="<%= dom_id event_management %>">
  <div class="card-header">
    Event Details
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <th scope="row">Title</th>
        <td><%= event_management.title %></td>
      </tr>
      <tr>
        <th scope="row">Description</th>
        <td><%= event_management.description %></td>
      </tr>
      <tr>
        <th scope="row">Start Time</th>
        <td><%= event_management.start_time %></td>
      </tr>
      <tr>
        <th scope="row">End Time</th>
        <td><%= event_management.end_time %></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/event_managements/_form.html.erb
<%= form_with(model: event_management) do |form| %>
  <% if event_management.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(event_management.errors.count, "error") %> prohibited this event_management from being saved:</h2>

      <ul>
        <% event_management.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :end_time, style: "display: block" %>
    <%= form.datetime_field :end_time, class: "form-control" %>
  </div>
<br/>
  <div class="form-group">
    <%= form.submit "Create Event", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/event_managements/edit.html.erb
<h1>Editing Event</h1>

<%= render "form", event_management: @event_management %>

<br>

<div>
  <%= link_to "Show this event management", @event_management , class:"btn btn-outline-success"%> |
  <%= link_to "Back to event managements", event_managements_path , class:"btn btn-outline-secondary" %>
</div>
<br/>

app/views/event_managements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 style="text-align:center;">Events</h1>

<%= link_to "New event ", new_event_management_path, class:"btn btn-outline-secondary", style:"margin-bottom:10px; margin-left:85%;" %>

<div id="event_managements">
  <% @event_managements.each do |event_management| %>
    <%= render event_management %>
    <p>
      <%= link_to "Show this event", event_management, class:"btn btn-outline-success" , style:"margin-top:10px;" %>
    </p>
  <% end %>
</div>

app/views/event_managements/new.html.erb
<div class="container">
<h1>New event </h1>

<%= render "form", event_management: @event_management %>

<br>

<div>
  <%= link_to "Back to event managements", event_managements_path , class:"btn btn-outline-secondary" %>
</div>
</div>

app/views/event_managements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event_management %>

<div>
  <%= link_to "Edit this event management", edit_event_management_path(@event_management) , class:"btn btn-outline-success"%> |
  <%= link_to "Back to event managements", event_managements_path , class:"btn btn-outline-secondary"%>

  <%= button_to "Destroy this event management", @event_management, method: :delete ,  class:"btn btn-outline-danger" , style:"margin-top:10px;" %>
</div>