config/routes.rb
Rails.application.routes.draw do
  resources :event_managements
  get 'calendar/home'
  resources :consultations
  resources :comments

devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  get '/users/sign_out'=> 'devise/sessions#destroy'
  get 'calendar/home'


end
  devise_for :users
  get "home/about" 
  get "posts/myposts"
  resources :posts

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
   
    validates :title, presence: true 
    validates :start_time, presence: true 
    validates :end_time, presence: true 
  
  end
  

app/models/event_management.rb
class EventManagement < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, presence: true, length: {minimum:5, maximum:100}
    validates :description, presence: true, length: {minimum:5, maximum:100}
    validates :keywords, presence: true, length: {minimum:5, maximum:100}

    has_many_attached :images
has_many :comments
    belongs_to :user

    before_create :randomized_id
         private

         def randomized_id
         begin 
          self.id = SecureRandom.random_number(1_000_000_000)
         end
         while User.where(id: self.id).exists?
           
         end
         
        end
        end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :posts
         has_many :comments

         before_create :randomized_id
         private

         def randomized_id
         begin 
          self.id = SecureRandom.random_number(1_000_000_000)
         end
         while User.where(id: self.id).exists?
           
         end
         
        end
        end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def about
    end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def home
    @event_management = EventManagement.where(
      start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_week
    )
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [:show, :edit, :update, :destroy]
  
    def index
      @events = Event.all
    end
  
    def new
      @event = Event.new
    end
  
    def create
      @event = Event.new(event_params)
      if @event.save
        redirect_to events_path, notice: "Event created successfully!"
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    def show
    end
  
    def edit
    end
  
    def update
      if @event.update(event_params)
        redirect_to events_path, notice: "Event updated successfully!"
      else
        render :edit, status: :unprocessable_entity
      end
    end
  
    def destroy
      @event.destroy
      redirect_to events_path, notice: "Event deleted successfully!"
    end
  
    private
  
    def set_event
      @event = Event.find(params[:id])
    end
  
    def event_params
      params.require(:event).permit(:title, :start_time, :end_time, :description)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def about
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  @comments = @post.comments.build
  end
  
  def myposts
   

   
    @posts = current_user.posts.all
  
  # GET /posts/new
end
  

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      # Try to access the nested post params, handling the case where it might be missing
      post_attributes = params.require(:post) rescue {}
      post_attributes.permit(:title, :user_id,:description, :keywords, images: [])
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.erb
<footer class=" bg-dark text-white text-center p-3">
  <div class="text-center">
    © 2024 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  </footer>

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag("post")%>
<nav class="navbar navbar-expand-lg navbar-dark bg-gradient-dark"> <%= link_to "Insta Clone", root_path, class:"navbar-brand text-white"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <%= link_to "Upload Post", new_post_path, class:"nav-link text-white" %>
    </li>
    <li class="nav-item">
      <%= link_to "About Us", home_about_path, class:"nav-link text-white"%>
    </li>
        <li class="nav-item">
    <%= link_to "Calender", calendar_home_path, class:"nav-link text-white" %>
     </li>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Account Settings
      </a>
      <div class="dropdown-menu bg-dark text-white">
        <%if user_signed_in?%>
          <%= link_to "Sign out", destroy_user_session_path, class:"nav-link text-white" %>
          <%= link_to "Edit Account", edit_user_registration_path, class:"nav-link text-white" %>
            <%= link_to "My Posts", posts_myposts_path, class:"nav-link text-white" %>
      
            
        <%else%>
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link text-white" %>
           <%= link_to "login", user_session_path, class:"nav-link text-white" %>
        </div>
    </li>
  
      <li class="nav-item">
        <a class="nav-link disabled text-white" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
  <%end%>
  
  </div>
</nav>


<script>
document.addEventListener('click', function (event) {
  const dropdownToggle = document.getElementById('navbarDropdown');
  if (event.target === dropdownToggle) {
    dropdownToggle.parentElement.classList.toggle('show');
  }
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-bidr0j[^`]*fnIqhfwVznB7EIlTAAeVZwQzTLTI9NkjmP0zodt5jnm3zMWQXWPElz" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>
      <%= render "layouts/footer" %>

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-bidr0j[^`]*fnIqhfwVznB7EIlTAAeVZwQzTLTI9NkjmP0zodt5jnm3zMWQXWPElz" crossorigin="anonymous"></script>

</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
  <span class="calendar-title" style="font-weight: bold; text-align: center;">
  <%= t('date.month_names')[start_date.month] %> <%= start_date.year %>
</span>


 <nav style="display: flex; justify-content: space-between; align-items: center;">
  <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view, class:"btn btn-primary" %>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view , class:"btn btn-primary"%>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view, class:"btn btn-primary" %>
</nav>

  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
   <time datetime="<%= start_date.strftime('%Y-%m') %>" class="calendar-title">
  <%= t('date.month_names')[start_date.month] %> <%= start_date.year %>
</time>

    <nav style="display: flex; justify-content: space-between; align-items: center;">
  <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view , class:"btn btn-primary" %>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view , class:"btn btn-primary"%>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view , class:"btn btn-primary"%>
</nav>

  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <span class="calendar-title" style="font-weight: bold; text-align: center;">
  <%= t('simple_calendar.week', default: 'Week') %>
  <%= calendar.week_number %>
  <% if calendar.number_of_weeks > 1 %>
    - <%= calendar.end_week %>
  <% end %>
</span>


   <nav style="display: flex; justify-content: space-between; align-items: center;">
  <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view , class:"btn btn-primary"%>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view , class:"btn btn-primary"%>
  <span style="margin: 0 10px;">  </span>
  <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view , class:"btn btn-primary"%>
</nav>

  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% instance_exec(day, calendar.sorted_events_for(day), &passed_block) %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>